from typing import Set, List, Dict, Tuple
import torch
import numpy as np
from collections import defaultdict
from sklearn.cluster import KMeans, AgglomerativeClustering
from sklearn.metrics.pairwise import cosine_similarity

from ...embedding import BaseEmbeddingModel
from .base import Node


class NodeClustering:
    """Clustering module for reasoning nodes based on embeddings."""
    
    def __init__(self, embedding_model: BaseEmbeddingModel, threshold: float = 0.8, method: str = 'cosine_similarity', 
                 tokenizer=None, enable_similarity_vote: bool = False, similarity_vote_weight: float = 0.0):
        """
        Initialize the clustering module.
        
        Args:
            embedding_model: Embedding model to use for encoding nodes
            threshold: Similarity threshold for clustering (0.0-1.0)
            method: Clustering method ('cosine_similarity', 'kmeans', 'hierarchical')
            tokenizer: Tokenizer for decoding sequences to text
            enable_similarity_vote: Whether to apply similarity voting to boost scores
            similarity_vote_weight: Weight for similarity vote boost (0.0-1.0)
        """
        self.embedding_model = embedding_model
        self.threshold = threshold
        self.method = method
        self.tokenizer = tokenizer
        self.enable_similarity_vote = enable_similarity_vote
        self.similarity_vote_weight = similarity_vote_weight
        
    def cluster_nodes(self, nodes: Set[Node]) -> Set[Node]:
        """
        Cluster nodes and return only the highest-scoring node from each cluster.
        
        Args:
            nodes: Set of nodes to cluster
            
        Returns:
            Set of nodes with only the best node from each cluster
        """
        if len(nodes) <= 1:
            print(f"[CLUSTERING DEBUG] Only {len(nodes)} node(s), skipping clustering")
            return nodes
            
        print(f"[CLUSTERING DEBUG] Starting clustering of {len(nodes)} nodes")
        print(f"[CLUSTERING DEBUG] Method: {self.method}, Threshold: {self.threshold}")
        print(f"[CLUSTERING DEBUG] Similarity voting: {self.enable_similarity_vote}, Weight: {self.similarity_vote_weight}")
        
        # Convert to list for indexing
        node_list = list(nodes)
        
        # Show original scores
        print(f"[CLUSTERING DEBUG] Original node scores: {[(node.id, getattr(node, 'reward_score', 'N/A')) for node in node_list]}")
        
        # Extract text from nodes
        node_texts = [self._extract_node_text(node) for node in node_list]
        
        # Debug: Show the actual text being compared
        print(f"[TEXT DEBUG] Extracted texts for clustering:")
        for i, (node, text) in enumerate(zip(node_list, node_texts)):
            print(f"[TEXT DEBUG] Node {node.id}: '{text[:100]}{'...' if len(text) > 100 else ''}'")
        
        # Get embeddings
        embeddings = self.embedding_model.encode(node_texts)
        
        # Apply clustering based on method
        if self.method == 'cosine_similarity':
            clusters = self._cosine_similarity_clustering(node_list, embeddings)
        elif self.method == 'kmeans':
            clusters = self._kmeans_clustering(node_list, embeddings)
        elif self.method == 'hierarchical':
            clusters = self._hierarchical_clustering(node_list, embeddings)
        else:
            raise ValueError(f"Unsupported clustering method: {self.method}")
        
        print(f"[CLUSTERING DEBUG] Formed {len(clusters)} clusters")
        for i, cluster in enumerate(clusters):
            cluster_scores = [getattr(node, 'reward_score', 'N/A') for node in cluster]
            print(f"[CLUSTERING DEBUG] Cluster {i}: {len(cluster)} nodes with scores {cluster_scores}")
        
        # Select best node from each cluster
        selected_nodes = set()
        for i, cluster in enumerate(clusters):
            if cluster:  # Skip empty clusters
                best_node = self._select_best_node(cluster)
                selected_nodes.add(best_node)
                print(f"[CLUSTERING DEBUG] Selected node {best_node.id} from cluster {i}")
        
        print(f"[CLUSTERING DEBUG] Clustering complete: {len(nodes)} → {len(selected_nodes)} nodes")
        return selected_nodes
    
    def _extract_node_text(self, node) -> str:
        """
        Extract text content from a node for embedding.
        
        Args:
            node: Node to extract text from
            
        Returns:
            Text string for embedding
        """
        # For SeqNode, we need to decode the sequence to text
        if hasattr(node, 'seq') and hasattr(node, 'len'):
            # Get the new tokens generated by this node
            if hasattr(node, 'this_seq'):
                # Use the new sequence part
                seq_tensor = node.this_seq
            else:
                # Fallback: use the full sequence
                seq_tensor = node.seq
            
            # Decode to text using the provided tokenizer
            if self.tokenizer is not None:
                try:
                    # Decode the sequence
                    text = self.tokenizer.decode(seq_tensor[0], skip_special_tokens=True)
                    return text
                except Exception:
                    # Fallback to sequence-based identifier
                    return f"node_sequence_{node.id}_{seq_tensor.shape}"
            else:
                # Fallback to sequence-based identifier
                return f"node_sequence_{node.id}_{seq_tensor.shape}"
        else:
            return f"node_{node.id}"
    
    def _cosine_similarity_clustering(self, nodes: List[Node], embeddings: torch.Tensor) -> List[List[Node]]:
        """
        Cluster nodes using cosine similarity threshold.
        
        Args:
            nodes: List of nodes
            embeddings: Tensor of embeddings
            
        Returns:
            List of clusters (each cluster is a list of nodes)
        """
        clusters = []
        used_indices = set()
        
        for i, node in enumerate(nodes):
            if i in used_indices:
                continue
                
            # Start a new cluster with this node
            cluster = [node]
            used_indices.add(i)
            
            # Find similar nodes
            for j, other_node in enumerate(nodes):
                if j in used_indices or i == j:
                    continue
                    
                similarity = self.embedding_model.compute_similarity(embeddings[i], embeddings[j])
                print(f"[SIMILARITY DEBUG] Node {node.id} vs Node {other_node.id}: similarity={similarity:.4f}, threshold={self.threshold}")
                if similarity >= self.threshold:
                    cluster.append(other_node)
                    used_indices.add(j)
                    print(f"[SIMILARITY DEBUG] → Clustered together!")
                else:
                    print(f"[SIMILARITY DEBUG] → Not clustered (below threshold)")
            
            clusters.append(cluster)
        
        return clusters
    
    def _kmeans_clustering(self, nodes: List[Node], embeddings: torch.Tensor) -> List[List[Node]]:
        """
        Cluster nodes using K-means clustering.
        
        Args:
            nodes: List of nodes
            embeddings: Tensor of embeddings
            
        Returns:
            List of clusters (each cluster is a list of nodes)
        """
        # Determine number of clusters (use a heuristic)
        n_clusters = min(max(1, len(nodes) // 2), len(nodes))
        
        # Convert to numpy for sklearn
        embeddings_np = embeddings.cpu().numpy()
        
        # Apply K-means
        kmeans = KMeans(n_clusters=n_clusters, random_state=42, n_init=10)
        cluster_labels = kmeans.fit_predict(embeddings_np)
        
        # Group nodes by cluster
        clusters = defaultdict(list)
        for node, label in zip(nodes, cluster_labels):
            clusters[label].append(node)
        
        return list(clusters.values())
    
    def _hierarchical_clustering(self, nodes: List[Node], embeddings: torch.Tensor) -> List[List[Node]]:
        """
        Cluster nodes using hierarchical clustering.
        
        Args:
            nodes: List of nodes
            embeddings: Tensor of embeddings
            
        Returns:
            List of clusters (each cluster is a list of nodes)
        """
        # Convert to numpy for sklearn
        embeddings_np = embeddings.cpu().numpy()
        
        # Determine number of clusters based on threshold
        # Use distance threshold instead of n_clusters
        distance_threshold = 1.0 - self.threshold
        
        # Apply hierarchical clustering
        clustering = AgglomerativeClustering(
            n_clusters=None,
            distance_threshold=distance_threshold,
            linkage='average',
            metric='cosine'
        )
        cluster_labels = clustering.fit_predict(embeddings_np)
        
        # Group nodes by cluster
        clusters = defaultdict(list)
        for node, label in zip(nodes, cluster_labels):
            clusters[label].append(node)
        
        return list(clusters.values())
    
    def _select_best_node(self, cluster: List[Node]) -> Node:
        """
        Select the best node from a cluster based on reward score.
        If similarity voting is enabled, boost the score based on cluster size and other nodes' scores.
        
        Args:
            cluster: List of nodes in the cluster
            
        Returns:
            Node with the highest (potentially boosted) reward score
        """
        if len(cluster) == 1:
            print(f"[VOTING DEBUG] Single node cluster, no voting needed")
            return cluster[0]
        
        if not self.enable_similarity_vote:
            # Original behavior: just find node with highest reward score
            best_node = max(cluster, key=lambda node: getattr(node, 'reward_score', 0.0))
            print(f"[VOTING DEBUG] Similarity voting disabled, selected node {best_node.id} with score {getattr(best_node, 'reward_score', 'N/A')}")
            return best_node
        
        print(f"[VOTING DEBUG] Similarity voting enabled for cluster of {len(cluster)} nodes")
        
        # Find the leader node (highest original score)
        leader_node = max(cluster, key=lambda node: getattr(node, 'reward_score', 0.0))
        leader_score = getattr(leader_node, 'reward_score', 0.0)
        
        # Calculate sum of scores from all other nodes in cluster
        other_nodes = [node for node in cluster if node != leader_node]
        other_scores_sum = sum(getattr(node, 'reward_score', 0.0) for node in other_nodes)
        
        # Boost leader node: leader_score + (sum_of_other_scores * weight)
        total_boost = other_scores_sum * self.similarity_vote_weight
        boosted_score = leader_score + total_boost
        
        print(f"[VOTING DEBUG] Leader node {leader_node.id}: original={leader_score:.4f}, other_scores_sum={other_scores_sum:.4f}, total_boost={total_boost:.4f}, final={boosted_score:.4f}")
        
        # Update leader node's score
        leader_node.original_reward_score = leader_score
        leader_node.reward_score = boosted_score
        
        print(f"[VOTING DEBUG] Updated leader node {leader_node.id} reward_score to {boosted_score:.4f}")
        
        return leader_node


def cluster_parallel_nodes(nodes: Set[Node], embedding_model: BaseEmbeddingModel, 
                          threshold: float = 0.8, method: str = 'cosine_similarity', tokenizer=None,
                          enable_similarity_vote: bool = False, similarity_vote_weight: float = 0.0) -> Set[Node]:
    """
    Convenience function to cluster parallel nodes.
    
    Args:
        nodes: Set of nodes to cluster
        embedding_model: Embedding model to use
        threshold: Similarity threshold for clustering
        method: Clustering method to use
        tokenizer: Tokenizer for decoding sequences to text
        enable_similarity_vote: Whether to apply similarity voting to boost scores
        similarity_vote_weight: Weight for similarity vote boost (0.0-1.0)
        
    Returns:
        Set of clustered nodes (best node from each cluster)
    """
    if not nodes or len(nodes) <= 1:
        return nodes
    
    clustering = NodeClustering(embedding_model, threshold, method, tokenizer, 
                               enable_similarity_vote, similarity_vote_weight)
    return clustering.cluster_nodes(nodes)
